
server:
   port: 8080
   servlet:
        #路径前缀
        context-path: /comment/v1

spring:
    rabbitmq:
        host: 10.172.46.9
        port: 5672
        username: admin
        password: admin

    datasource:
        name: test
        #url: jdbc:mysql://127.0.0.1:3306/mytest?useUnicode=true&characterEncoding=UTF-8&allowMultiQueries=true
        url: jdbc:mysql://127.0.0.1:3306/comment_system?useUnicode=true&characterEncoding=UTF-8&allowMultiQueries=true
        username: test
        password: test
        # 使用druid数据源
        type: com.alibaba.druid.pool.DruidDataSource
        driver-class-name: com.mysql.jdbc.Driver
        filters: stat
        maxActive: 20
        initialSize: 1
        maxWait: 60000
        minIdle: 1
        timeBetweenEvictionRunsMillis: 60000
        minEvictableIdleTimeMillis: 300000
        validationQuery: select 'x'
        testWhileIdle: true
        testOnBorrow: false
        testOnReturn: false
        poolPreparedStatements: true
        maxPoolPreparedStatementPerConnectionSize: 20
        maxOpenPreparedStatements: 20

mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.netease.comment.model


mapper:
  mappers:  com.netease.comment.mapper
  not-empty: false
  identity: MYSQL


# redis
ncr:
  host : 127.0.0.1
  port : 6379
  password : 123456
  # socket超时时间(毫秒默认2000）
  timeout : 3000
  # 最大能够保持idle状态的连接数（默认值8）
  maxIdle : 100
  # 最小保持idle状态的连接数（默认值0）
  minIdle : 5
  # 最大分配的连接数（默认值8）
  maxTotal : 100
  # 获取连接的超时时间(毫秒)
  maxWait : 3000
  # 连接耗尽时是否阻塞, false报异常,ture阻塞直到超时, 默认true
  blockWhenExhausted : true

#评论缓存数设置
comment:
  cache:
     number: 30

#易盾评论信息校验地址
yidun:
  content:
    secret-id: 6bbcd1cd918e87e6c141b2895905e235
    secretkey: 89f3507e6bafe9beccaa32effe7772f2
    business-id: a9c5b4197f2e1c2d31f53e074798f0c8
    api-url: https://as.dun.163yun.com/v3/text/check
  pic:
    secret-id: 6bbcd1cd918e87e6c141b2895905e235
    secretkey: 89f3507e6bafe9beccaa32effe7772f2
    business-id: 4fc3b4ed3f74da054b92e6f989944186
    api-url: https://as.dun.163yun.com/v3/image/check


#rabbitMq
rabbitmq:
  consumer:
    queue: rec_info_comment
    exchange: rec_info_comment_exchange
    routKey: rec_info_comment_routKey
  producer:
    exchange: rec_info_comment_exchange
    routKey: rec_info_comment_routKey
